#
# Prefix
#
set -g prefix C-a
unbind C-b
bind C-a send-prefix

#
# Options
#
set -g allow-rename off
set -g base-index 1
set -g escape-time 0
set -g focus-events on
set -g history-limit 5000000
set -g mouse on
set -g pane-base-index 1
set -g renumber-windows on
set -g repeat-time 0
set -g set-clipboard on
set -g status-bg black
set -g status-fg white
set -g status-position top
setw -g remain-on-exit off

#
# Vi / copy mode
#
set -g mode-keys vi
set -g status-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
if-shell "uname | grep -q Darwin" \
  "bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe 'pbcopy'" \
  "bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe 'xclip -sel clipboard'"

#
# Key bindings
#
bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key f command-prompt -p "find-window:" "find-window -i '%%'"
bind-key -n M-f display-popup -E -w 90% -h 80% "zsh -c 'cds f'"

bind-key -T prefix e display-popup -E -h "80%" -w "80%" \
  "tmux new-session -As Notes 'notes today'"
